### Imports

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)
print("cuda: {}".format(torch.cuda.is_available()))

1.13.1+cu116
cuda: True


### Tensor Basics

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7,8], 
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
TENSOR = torch.tensor([[[1,2,3], 
                        [3,6,9],
                        [2,4,5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

In [17]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7007, 0.5072, 0.0716, 0.6917],
        [0.8297, 0.3766, 0.7762, 0.0357],
        [0.7525, 0.0560, 0.1759, 0.3555]])

In [18]:
random_tensor.ndim

2

In [19]:
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, RGB
random_image_tensor.shape

torch.Size([224, 224, 3])

In [20]:
random_image_tensor.ndim

3

### Zeros and Ones

In [21]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(size=(3,4))
ones.dtype

torch.float32

### Range Tensors and Tensor like

In [24]:
torch.range(0,10)

C:\Users\mohse\AppData\Local\Temp\ipykernel_2880\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [31]:
one_to_ten = torch.arange(1,11)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Datatypes and attributes

In [32]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float32_tensor.dtype

torch.float32

In [33]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float16_tensor.dtype

torch.float16

In [36]:
tsr = torch.tensor([3.0,6.0,9.0], dtype=torch.float32, 
                                    device=None,
                                    requires_grad=False)
tsr, tsr.dtype, tsr.device, tsr.requires_grad

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'), False)

In [38]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") 

tensor([[0.3392, 0.2112, 0.2754, 0.7264],
        [0.4663, 0.8505, 0.5830, 0.8164],
        [0.3734, 0.6001, 0.5669, 0.4123]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [41]:
float16_tensor * float32_tensor

tensor([ 9., 36., 81.])

In [42]:
int32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
float32_tensor * int32_tensor

tensor([ 9., 36., 81.])

### Tensor Operations

In [44]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [47]:
tensor * 10, tensor/10, tensor-3

(tensor([10, 20, 30]), tensor([0.1000, 0.2000, 0.3000]), tensor([-2, -1,  0]))

In [48]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [49]:
tensor.add(9)

tensor([10, 11, 12])

In [50]:
tensor * tensor

tensor([1, 4, 9])

### Matrix Multiplication

In [54]:
tensor

tensor([1, 2, 3])

In [52]:
torch.matmul(tensor, tensor)

tensor(14)

In [53]:
1*1 + 2*2 + 3*3

14

In [56]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)    

tensor(14)
CPU times: total: 0 ns
Wall time: 9.54 ms


In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)