### Imports

In [10]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
print(torch.__version__)
print("cuda: {}".format(torch.cuda.is_available()))

1.13.1+cu116
cuda: True


### Tensor Basics

In [36]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [16]:
scalar.ndim

0

In [18]:
scalar.item()

7

In [20]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [21]:
vector.ndim

1

In [22]:
vector.shape

torch.Size([2])

In [23]:
MATRIX = torch.tensor([[7,8], 
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [24]:
MATRIX.ndim

2

In [26]:
MATRIX.shape

torch.Size([2, 2])

In [28]:
MATRIX[1]

tensor([ 9, 10])

In [29]:
TENSOR = torch.tensor([[[1,2,3], 
                        [3,6,9],
                        [2,4,5]]])

In [30]:
TENSOR.ndim

3

In [32]:
TENSOR.shape

torch.Size([1, 3, 3])

In [34]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

In [37]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9067, 0.2844, 0.2043, 0.6216],
        [0.1083, 0.1810, 0.7534, 0.4398],
        [0.0630, 0.1225, 0.1170, 0.6547]])

In [38]:
random_tensor.ndim

2

In [41]:
random_image_tensor = torch.rand(size=(224,224,3)) # height, width, RGB
random_image_tensor.shape

torch.Size([224, 224, 3])

In [42]:
random_image_tensor.ndim

3

### Zeros and Ones

In [43]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [44]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
ones = torch.ones(size=(3,4))
ones.dtype

torch.float32